version: '3.1'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: odoo
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - odoo15-network

  odoo15:
    image: odoo:15
    depends_on:
      - db
    ports:
      - "8070:8069"  # استخدام منفذ مختلف مثل 8070 بدلاً من 8069
    volumes:
      - odoo-web-data:/var/log/odoo:rw
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    networks:
      - odoo15-network

volumes:
  db-data:
  odoo-web-data:

networks:
  odoo15-network:
